name: Run Postman API Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Start server in background
        run: |
          cd backend
          nohup npm run dev > server.log 2>&1 &

      - name: Wait for server to be ready
        run: |
          for i in {1..10}; do
            if curl --output /dev/null --silent --head --fail http://localhost:5000/health; then
              echo "Server is up!"
              exit 0
            fi
            echo "Waiting for server..."
            sleep 5
          done
          echo "Server did not start in time." && exit 1

      - name: Install Newman
        run: npm install -g newman

      - name: Run API tests
        run: |
          newman run postman-tests.json -e postman_environment.json
